create database customer_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, sum(purchased_amount)  AS revenu 
FROM customers GROUP BY gender; 

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchased_amount FROM customers
WHERE discount_applied = 'Yes' AND purchased_amount >= (Select avg(purchased_amount) FROM customers);

-- Q3. Which are the top 5 products with the highest average review rating
SELECT round(AVG(review_rating),2) AS AVG_rating , item_purchased From customers 
group by item_purchased  order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
Select shipping_type, round(avg(purchased_amount),2) as AVG_time FROM customers
where shipping_type in ('Express', 'Standard')group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT round(sum(purchased_amount),2) AS total_revenue, 
round(avg(purchased_amount),2) AS avg_spends, subscription_status 
FROM customers group by subscription_status
order by total_revenue, avg_spends;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100.0 * sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ count(*), 2) AS discount_rate
FROM customers group by item_purchased 
order by sum(purchased_amount) desc limit 5;














